config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, except: [:new]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :users do
    member { get :following, :followers }
  end
end

app/views/layouts/_head.html.haml
%head
  %title RailsTutorial
  %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
  = stylesheet_link_tag "application", "data-turbo-track": "reload"
  = javascript_importmap_tags

app/views/layouts/_header.html.haml
- if logged_in?
  %header.grid.grid-cols-11.p-10.text-center.place-items-center.bg-red-400.rounded-lg
- else
  %header.grid.grid-cols-11.p-10.text-center.place-items-center.bg-red-400.rounded-lg
= link_to "sample app", root_path, id: "logo", class:"font-extrabold text-4xl col-span-2"
= link_to "Home",   root_path ,class:"font-extrabold text-lg col-start-5"
= link_to "Help",   help_path ,class:"font-extrabold text-lg"
= link_to "About", about_path ,class:"font-extrabold text-lg"
= link_to "Contact", contact_path ,class:"font-extrabold text-lg"
- if logged_in?
  = button_to "Log out", logout_path, method: :delete ,class:"font-extrabold text-lg"
  = link_to "Users", users_path ,class:"font-extrabold text-lg"
  = link_to "Settings", edit_user_path(current_user),class:"font-extrabold text-lg"
  = link_to "profile", current_user ,class:"font-extrabold text-lg"
- else
  = link_to "signup", signup_path ,class:"font-extrabold text-lg"
  = link_to "login", login_path ,class:"font-extrabold text-lg"

app/views/layouts/application.html.haml
!!!
%html
  %body
    = render 'layouts/head'
    %main.m-10
      = render 'layouts/header'
      - flash.each do |message_type, message|
        %div{:class => "alert alert-#{message_type} text-center my-20 p-10 bg-lime-400"}= message
      .text-center.my-40
        = yield
        .bg-slate-100.m-20.p-20.shadow-2xl
          = debug(params) if Rails.env.development?